apiVersion: apps/v1
kind: deployment
metadata:
  name: grafana-deployment
  labels:
    app: grafana
  
spec:
  containers:
    - name: grafana-container
      image: localhost/grafana:latest
      ports:
        - containerPort: 3000
